function detail(id,w){const s=data.staff.find(x=>x.id===id),st=stats(s,w),h=hoursByDay(st.ps),ds=days(w).slice(0,5),mx=Math.max(9,...Object.values(h));
 const trend=[-3,-2,-1,0].map(o=>{const k=dk(monday(new Date(w+'T00:00:00'),o));return{k,sc:stats(s,k).score}});
 const nt=data.notes.filter(x=>x.uid===id&&(x.key===w||days(w).some(d=>dk(d)===x.key))).sort((a,b)=>a.key<b.key?-1:1);
 const stars=i=>[1,2,3,4,5].map(v=>`<button class="${ev.q[i]===v?'on':'g'}" onclick="ev.q[${i}]=${v};ev.keep=1;render()">${v}</button>`).join(' ');
 if(ev.id!==id+w){ev={id:id+w,q:st.e?.q||[3,3,3],c:st.e?.comment||''}}
 return`<div class="row" style="margin-bottom:10px"><button class="g" onclick="view='team';render()">← Team</button><h2 style="margin:0">${esc(s.name)} <span class="mu">${esc(s.dept)} · badge ${esc(s.badge||'—')}</span></h2></div>
 <div class="grid"><div class="card"><h2>Hours by day</h2><svg viewBox="0 0 300 140" width="100%">${ds.map((d,i)=>{const v=h[dk(d)]||0,bh=v/mx*100;return`<rect x="${i*60+12}" y="${110-bh}" width="36" height="${bh}" rx="5" fill="var(--ac)"/><text x="${i*60+30}" y="125" text-anchor="middle" font-size="11" fill="var(--mu)">${d.toLocaleDateString([],{weekday:'short'})}</text><text x="${i*60+30}" y="${104-bh}" text-anchor="middle" font-size="11" fill="currentColor">${v?v.toFixed(1):''}</text>`}).join('')}</svg><div>${chips(st,w)}</div><div class="mu">${st.full} of ${st.exp} days = <b>${Math.round(st.att)}%</b> · ${st.hrs.toFixed(1)} h worked</div></div>
 <div class="card"><h2>Score trend (4 weeks)</h2><svg viewBox="0 0 300 140" width="100%">${trend.map((t,i)=>`<rect x="${i*72+16}" y="${110-t.sc}" width="44" height="${t.sc}" rx="5" fill="${col(t.sc)}"/><text x="${i*72+38}" y="${104-t.sc}" text-anchor="middle" font-size="12" fill="currentColor">${Math.round(t.sc)}</text><text x="${i*72+38}" y="127" text-anchor="middle" font-size="10" fill="var(--mu)">${t.k.slice(5)}</text>`).join('')}</svg></div>
 <div class="card"><h2>Evaluation (this week)</h2><div class="mu">Quality of work</div>${stars(0)}<div class="mu" style="margin-top:8px">Productivity</div>${stars(1)}<div class="mu" style="margin-top:8px">Teamwork &amp; initiative</div>${stars(2)}<label>Comment</label><textarea id="ec">${esc(ev.c)}</textarea><br><br><button onclick="saveEval('${id}','${w}')">Save evaluation</button></div></div>
 <div class="card" style="margin-top:14px"><h2>Plans &amp; reports this week</h2>${nt.length?nt.map(n=>`<p><b>${n.kind.replace('-',' ')}</b> <span class="mu">${n.key}</span><br>${esc(n.text)||'<i class="mu">empty</i>'}</p>`).join(''):'<p class="mu">Nothing submitted.</p>'}</div>
 <div class="card wrap" style="margin-top:14px"><h2>Time log — shift ${shift().start} to ${shift().end}</h2>${timeTable(st,w)}</div>`}
async function saveEval(id,w){const q=ev.q,c=$('#ec').value;await db.collection('evals').doc(id+'_'+w).set({uid:id,week:w,q,comment:c,rating:q.reduce((a,b)=>a+b,0)/3});ev.id=null}
