function manager(w){if(!mgr)return`<div class="card" style="max-width:520px;margin:40px auto"><h2>Access denied</h2><p class="mu">This dashboard is for managers only.</p></div>`;
 const tabs=`<div class="tabs">${[['team','Team overview'],['people','Employees'],['detail','Employee detail'],['device','Hikvision device']].map(([k,l])=>`<button class="${view===k?'on':'g'}" onclick="view='${k}';render()">${l}</button>`).join('')}</div>`;
 if(view==='device')return tabs+device();
 if(view==='people')return tabs+people();
 if(view==='detail'&&sel&&data.staff.find(x=>x.id===sel))return tabs+detail(sel,w);
 const dp=[...new Set(data.staff.filter(s=>!s.mgr).map(s=>s.dept).filter(Boolean))],o=(v,l,c)=>`<option value="${v}" ${c===v?'selected':''}>${l}</option>`;
 return tabs+`<div class="card row" style="margin-bottom:14px"><input id="fq" placeholder="🔍 Search name, department or badge…" value="${esc(F.q)}" oninput="F.q=this.value;dash()" style="flex:2;min-width:200px"><select onchange="F.d=this.value;dash()">${o('','All departments',F.d)+dp.map(d=>o(esc(d),esc(d),F.d)).join('')}</select><select onchange="F.f=this.value;dash()">${o('','All employees',F.f)+o('in','In now',F.f)+o('low','Attendance below 80%',F.f)+o('norep','Reports below 60%',F.f)}</select><select onchange="F.s=this.value;dash()">${o('score','Sort: score',F.s)+o('att','Sort: attendance',F.s)+o('name','Sort: name',F.s)}</select></div><div id="dash">${dashHtml(w)}</div>`}
function dash(){$('#dash').innerHTML=dashHtml(wkey())}
function dashHtml(w){const q=F.q.toLowerCase();
 const rows=data.staff.filter(s=>!s.mgr&&s.active!==false&&!s.id.startsWith('inv:')).map(s=>({s,...stats(s,w)})).filter(r=>(!q||(r.s.name+' '+r.s.dept+' '+r.s.badge).toLowerCase().includes(q))&&(!F.d||r.s.dept===F.d)&&(F.f!=='in'||status(r.s.id))&&(F.f!=='low'||r.att<80)&&(F.f!=='norep'||r.rep<60))
  .sort((a,b)=>F.s==='name'?a.s.name.localeCompare(b.s.name):b[F.s]-a[F.s]);
 const avg=k=>rows.length?Math.round(rows.reduce((a,r)=>a+r[k],0)/rows.length):0,ds=days(w).slice(0,5);
 const pres=ds.map(d=>rows.filter(r=>r.by[dk(d)]).length),full=ds.map(d=>rows.filter(r=>(r.by[dk(d)]||[]).includes('out')).length),mx=Math.max(1,rows.length);
 const tr=[-5,-4,-3,-2,-1,0].map(o=>{const k=dk(monday(new Date(w+'T00:00:00'),o));return{k,v:rows.length?rows.reduce((a,r)=>a+stats(r.s,k).att,0)/rows.length:0}});
 const ch1=`<svg viewBox="0 0 300 150" width="100%">${ds.map((d,i)=>{const h=pres[i]/mx*100;return`<rect x="${i*58+14}" y="${115-h}" width="34" height="${h}" rx="5" fill="var(--ac)"/><text x="${i*58+31}" y="${109-h}" text-anchor="middle" font-size="12" fill="currentColor">${pres[i]}</text><text x="${i*58+31}" y="132" text-anchor="middle" font-size="11" fill="var(--mu)">${d.toLocaleDateString([],{weekday:'short'})}</text>`}).join('')}</svg>`;
 const ch2=`<svg viewBox="0 0 300 ${rows.length*24+8}" width="100%">${rows.map((r,i)=>`<text x="0" y="${i*24+17}" font-size="11" fill="currentColor">${esc(r.s.name.slice(0,13))}</text><rect x="92" y="${i*24+6}" width="150" height="12" rx="6" fill="var(--bd)"/><rect x="92" y="${i*24+6}" width="${r.att*1.5}" height="12" rx="6" fill="${col(r.att)}"/><text x="248" y="${i*24+17}" font-size="11" fill="currentColor">${r.full}/${r.exp} · ${Math.round(r.att)}%</text>`).join('')}</svg>`;
 const pts=tr.map((t,i)=>[20+i*52,105-t.v*0.9]);
 const ch3=`<svg viewBox="0 0 300 150" width="100%"><polyline fill="none" stroke="var(--ac)" stroke-width="3" points="${pts.map(p=>p.join(',')).join(' ')}"/>${tr.map((t,i)=>`<circle cx="${pts[i][0]}" cy="${pts[i][1]}" r="4" fill="var(--ac)"/><text x="${pts[i][0]}" y="${pts[i][1]-9}" text-anchor="middle" font-size="11" fill="currentColor">${Math.round(t.v)}%</text><text x="${pts[i][0]}" y="132" text-anchor="middle" font-size="10" fill="var(--mu)">${t.k.slice(5)}</text>`).join('')}</svg>`;
 return`<div class="grid" style="margin-bottom:14px"><div class="card"><div class="mu">Employees (filtered)</div><div class="big">${rows.length}</div></div><div class="card"><div class="mu">Currently in</div><div class="big">${rows.filter(r=>status(r.s.id)).length}</div></div><div class="card"><div class="mu">Avg attendance</div><div class="big" style="color:${col(avg('att'))}">${avg('att')}%</div></div><div class="card"><div class="mu">Avg score</div><div class="big">${avg('score')}</div></div></div>
 <div class="grid" style="margin-bottom:14px"><div class="card"><h2>Employees present per day</h2>${ch1}</div><div class="card"><h2>Attendance by employee (days)</h2>${rows.length?ch2:'<p class="mu">No data</p>'}</div><div class="card"><h2>Team attendance trend (6 weeks)</h2>${ch3}</div></div>
 <div class="card wrap"><h2>Team performance — click a row</h2><table><tr><th>Employee</th><th>Now</th><th>Days</th><th>Attendance</th><th>Punctual</th><th>Today</th><th>Reports</th><th>Rating</th><th>Score</th></tr>
 ${rows.map(r=>`<tr class="c" onclick="sel='${r.s.id}';view='detail';render()"><td><b>${esc(r.s.name)}</b><div class="mu">${esc(r.s.dept)}</div></td><td><span class="dot" style="background:${status(r.s.id)?'var(--ok)':'var(--mu)'}"></span>${status(r.s.id)?'In':'Out'}</td><td>${r.full}/${r.exp}<div>${chips(r,w)}</div></td><td>${Math.round(r.att)}%${bar(r.att)}</td><td>${Math.round(r.pun)}%</td><td>${todayStr(r)}</td><td>${Math.round(r.rep)}%${bar(r.rep)}</td><td>${r.rt?r.rt.toFixed(1):'—'}</td><td><b style="color:${col(r.score)}">${Math.round(r.score)}</b></td></tr>`).join('')||'<tr><td colspan="9" class="mu">No employees match. Employees create a profile on their first visit.</td></tr>'}</table></div>${leaderboard(w)}`}
