function people(){const e=editId&&data.staff.find(x=>x.id===editId)||{};
 return`<div class="grid"><div class="card"><h2>${editId?'Edit employee':'Add employee'}</h2><label>Full name</label><input id="pn" value="${esc(e.name)}"><label>Work email (their login)</label><input id="pe" type="email" value="${esc(e.email)}"><label>Department</label><input id="pd" value="${esc(e.dept)}"><div class="row"><div style="flex:1"><label>Badge / employee No.</label><input id="pb" value="${esc(e.badge)}"></div><div style="flex:1"><label>Days per week</label><input id="pdy" type="number" min="1" max="7" value="${e.days||5}"></div></div><br><label>Password (leave blank for random code)</label><input id="ppw" type="text" value=""><br><div class="row"><button onclick="saveEmp()">Save</button>${editId?'<button class="g" onclick="editId=null;render()">Cancel</button>':''}<span id="pmsg" class="mu"></span></div></div>
 <div class="card"><h2>Bulk import</h2><textarea id="pbulk" placeholder="name,email,department,badge,days&#10;Sara Ali,sara@iracktech.com,Sales,1001,5"></textarea><div class="row" style="margin-top:8px"><button onclick="bulkEmp()">Import list</button><span id="pbm" class="mu"></span></div></div>
 <div class="card"><h2>How employees log in</h2><ol class="mu" style="padding-left:18px;margin:0"><li>Add the employee here with their work email.</li><li>Use this page’s <b>Share</b> menu to invite the same emails (contributor access).</li><li>They sign in with their own account and enter their email + the password/code shown next to “Invited” (only needed the first time).</li><li>People not on this list see “Account not registered”.</li></ol></div><div class="card"><h2>Working hours</h2><label>Punch in by</label><input id="sst" type="time" value="${shift().start}"><label>Punch out from</label><input id="sen" type="time" value="${shift().end}"><br><br><div class="row"><button onclick="saveShift()">Save</button><span id="shm" class="mu"></span></div><p class="mu">Early arrival and overtime are allowed and shown.</p></div></div>
 <div class="card wrap" style="margin-top:14px"><div class="row" style="justify-content:space-between"><h2>Employees (${data.staff.filter(s=>!s.mgr).length})</h2><input id="pq" placeholder="🔍 Search…" style="max-width:240px" value="${esc(pq)}" oninput="pq=this.value;plist()"></div><div id="plist">${plist(1)}</div></div>`}
function plist(ret){const q=pq.toLowerCase(),rows=data.staff.filter(s=>!s.mgr&&(s.name+' '+s.email+' '+s.dept+' '+s.badge).toLowerCase().includes(q)).sort((a,b)=>(a.name||'').localeCompare(b.name||''));
 const h=`<table><tr><th>Name</th><th>Email</th><th>Dept</th><th>Badge</th><th>Days</th><th>Status</th><th></th></tr>${rows.map(r=>{const inv=r.id.startsWith('inv:'),st=inv?'Invited':r.active===false?'Inactive':'Active';return`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.email)}</td><td>${esc(r.dept)}</td><td>${esc(r.badge)||'—'}</td><td>${r.days}</td><td><span class="chip ${st==='Active'?'full':st==='Invited'?'part':'none'}">${st}</span>${inv?` <span class="mu">pwd <b>${esc(r.code)}</b></span>`:''}</td><td class="row">${inv?'':`<button class="g" onclick="sel='${r.id}';view='detail';render()">View</button>`}<button class="g" onclick="editId='${r.id}';render()">Edit</button><button class="g" onclick="toggleEmp('${r.id}')">${r.active===false?'Activate':'Deactivate'}</button><button class="g" onclick="rmEmp('${r.id}')">${rmArm===r.id?'Confirm?':'Remove'}</button></td></tr>`}).join('')||'<tr><td colspan="7" class="mu">No employees yet — add your first one above.</td></tr>'}</table>`;
 if(ret)return h;$('#plist').innerHTML=h}
async function saveEmp(){const g=i=>$('#'+i)?$('#'+i).value.trim():'',email=g('pe').toLowerCase(),o={name:g('pn'),email,dept:g('pd'),badge:g('pb'),days:Math.min(7,Math.max(1,+g('pdy')||5))};
 if(!o.name||!okMail(email)){$('#pmsg').textContent='Name and a valid @iracktech.com email are required';return}
 if(editId){await db.collection('staff').doc(editId).update(o);editId=null;return render()}
 if(data.staff.some(x=>x.email===email)){$('#pmsg').textContent='This email already exists';return}
 const pwd = g('ppw') || cd();
 await db.collection('staff').doc('inv:'+email).set({...o,active:true,invited:Date.now(),code:pwd});render()}
async function bulkEmp(){let n=0,k=0;for(const l of $('#pbulk').value.split('\n')){const c=l.split(',').map(x=>x.trim()),email=(c[1]||'').toLowerCase();
  if(!c[0]||!okMail(email)||data.staff.some(x=>x.email===email)){if(l.trim())k++;continue}
  await db.collection('staff').doc('inv:'+email).set({name:c[0],email,dept:c[2]||'',badge:c[3]||'',days:Math.min(7,Math.max(1,+c[4]||5)),active:true,invited:Date.now(),code:cd()});n++}
 render();$('#pbm')&&($('#pbm').textContent=`Added ${n}, skipped ${k}`)}
async function toggleEmp(id){const r=data.staff.find(x=>x.id===id);await db.collection('staff').doc(id).update({active:r.active===false})}
async function rmEmp(id){if(rmArm!==id){rmArm=id;plist();return}rmArm=null;await db.collection('staff').doc(id).delete()}
